# Generated by Django 4.2.7 on 2023-11-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="products/%Y/%m/%d/"),
                ),
                ("name", models.CharField(max_length=55)),
                ("description", models.CharField(max_length=255)),
                ("price", models.FloatField()),
            ],
        ),
    ]
