# Generated by Django 4.2.7 on 2023-11-10 14:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cyborg", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={"verbose_name": "Product"},
        ),
    ]
