# Generated by Django 4.2.7 on 2023-11-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cyborg", "0002_alter_products_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="off",
            field=models.BooleanField(default=False),
        ),
    ]
